export const state = () => ({
    Products:{
        cleaning:[
            {
                name:"Samsung P1494 Washing Machine - 9 Kg",
                id:"P1494",
                images:[
                    {
                        address:"/images/category/House/cleaning/P1494.jpg",
                    }
                ],
                price:"27,500,000",
                special:false,
                discount:"",
                realPrice:"",
                brand:"Samsung"
            },
            {
                name:"Xiaomi cordless vacuum cleaner model 1C",
                id:"1C",
                images:[
                    {
                        address:"/images/category/House/cleaning/1C.jpg",
                    }
                ],
                price:"6,500,000",
                special:true,
                discount:"10%",
                realPrice:"7,200,000",
                brand:"Xiaomi"
            },
            {
                name:"GPlus GDW-J552S Dishwasher",
                id:"GDW-J552S",
                images:[
                    {
                        address:"/images/category/House/cleaning/GDW-J552S.jpg",
                    }
                ],
                price:"14,575,000",
                special:true,
                discount:"7%",
                realPrice:"15,700,000",
                brand:"GPlus"
            },
        ],
        "video-audio":[
            {
                name:"Gplus GTV-50LU722S Smart LED TV 50 Inch",
                id:"GTV-50LU722S",
                images:[
                    {
                        address:"/images/category/House/video_and_audio/GTV-50LU722S.jpg",
                    }
                ],
                price:"9,950,000",
                special:true,
                discount:"6%",
                realPrice:"10,550,000",
                brand:"Gplus"
            },
            {
                name:"Sony Playstation 5 game console with a capacity of 825 GB",
                id:"Playstation_5",
                images:[
                    {
                        address:"/images/category/House/video_and_audio/Playstation_5.jpg",
                    }
                ],
                price:"27,895,000",
                special:false,
                discount:"",
                realPrice:"",
                brand:"Sony"
            },
            {
                name:"Sony PlayStation 5 PLUS 3D gaming headset",
                id:"PLUS_3D",
                images:[
                    {
                        address:"/images/category/House/video_and_audio/PLUS_3D.jpg",
                    }
                ],
                price:"3,295,000",
                special:false,
                discount:"",
                realPrice:"",
                brand:"Sony"
            },
        ]
    }
})