export default () => ({
    specialBrands:["Xiaomi","Samsung","Adidas","Sony"],
    allCategories:{
        "Digital products":
            {
                address:"/images/category/Digital/cover.jpg",
                route:"/Products/category/Digital",
                products:{
                    mobile:{
                        cover:"/images/category/Digital/mobile/cover.png",
                        route:"/Products/Digital/mobile",
                    },
                    laptop:{
                        cover:"/images/category/Digital/laptop/cover.png",
                        route:"/Products/Digital/laptop",
                    }
                }
            }
        ,
        "Fashion and clothing":
            {
                address:"/images/category/Fashion/cover.jpg",
                route:"/Products/category/Fashion",
                products:{
                    female:{
                        cover:"/images/category/Fashion/female/cover.png",
                        route:"/Products/Fashion/female",
                    },
                    male:{
                        cover:"/images/category/Fashion/male/cover.png",
                        route:"/Products/Fashion/male",
                    }
                }
            }
        ,
        "House":
            {
                address:"/images/category/House/cover.jpg",
                route:"/Products/category/House",
                products:{
                    cleaning:{
                        cover:"/images/category/House/cleaning/cover.png",
                        route:"/Products/House/cleaning",
                    },
                    "video-audio":{
                        cover:"/images/category/House/video_and_audio/cover.png",
                        route:"/Products/House/video-audio",
                    }
                }
            }
        ,
        "Beauty and health":
            {
                address:"/images/category/Beauty/cover.jpg",
                route:"/Products/category/Beauty",
                products:{
                    health:{
                        cover:"/images/category/Beauty/Health/cover.png",
                        route:"/Products/Beauty/health",
                    },
                    makeup:{
                        cover:"/images/category/Beauty/makeup/cover.png",
                        route:"/Products/Beauty/makeup",
                    }
                }
            }
        
    }
})